[package]
name = "nitro_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.8", features = ["std", "serde"] }
text_trees = { version = "0.1.2" }
serde_json = "1.0.70"
serde = { version = "1.0.130", features = ["derive"] }
[[test]]
name = "normal"
harness = false